# Generated by Django 4.2.30 on 2026-08-28 21:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Student's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Student's last name", max_length=100)),
                ('form_class', models.CharField(help_text='Form class (e.g., 7A, 8B)', max_length=10)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Trip name', max_length=200)),
                ('destination', models.CharField(help_text='Trip destination', max_length=200)),
                ('trip_date', models.DateField(help_text='Date of the trip')),
                ('departure_time', models.TimeField(help_text='Time of departure')),
                ('return_time', models.TimeField(help_text='Time of return')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost per student in GBP', max_digits=6)),
                ('permission_deadline', models.DateField(help_text='Deadline for permission forms')),
                ('packed_lunch_required', models.BooleanField(default=True, help_text='Whether students need to bring a packed lunch')),
                ('year_group', models.CharField(help_text='Year group (e.g., Year 7, Year 8)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this trip', on_delete=django.db.models.deletion.CASCADE, related_name='trips_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-trip_date'],
                'permissions': [('can_manage_trips', 'Can create and edit trips')],
            },
        ),
        migrations.CreateModel(
            name='TripResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_returned', models.BooleanField(default=False, help_text='Whether the permission slip was returned')),
                ('date_returned', models.DateField(blank=True, help_text='Date the permission slip was returned', null=True)),
                ('payment_received', models.BooleanField(default=False, help_text='Whether payment has been received')),
                ('emergency_contact_number', models.CharField(help_text='Emergency contact phone number (UK format)', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_uk_phone', message='Please enter a valid UK phone number (e.g., 07123456789 or +44 7123 456789)', regex='^(\\+44|0)[0-9\\s\\-\\(\\)]{9,}$')])),
                ('medical_needs', models.TextField(blank=True, help_text='Any medical needs or allergies')),
                ('parent_signature_name', models.CharField(blank=True, help_text='Parent/Guardian name for signature (digital record)', max_length=200)),
                ('consent_given', models.BooleanField(default=False, help_text='Whether parental consent has been given')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_responses', to='trips.student')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Response',
                'verbose_name_plural': 'Trip Responses',
                'ordering': ['trip', 'student'],
                'unique_together': {('trip', 'student')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='trips',
            field=models.ManyToManyField(related_name='students', through='trips.TripResponse', to='trips.trip'),
        ),
    ]
