# Generated by Django 4.2.30 on 2026-08-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='year_group',
            field=models.CharField(choices=[('Year 8', 'Year 8'), ('Year 9', 'Year 9'), ('Year 10', 'Year 10'), ('Year 11', 'Year 11'), ('Year 12', 'Year 12'), ('Year 13', 'Year 13'), ('Year 14', 'Year 14')], help_text='Year group', max_length=50),
        ),
    ]
